### ISSUE TITLE
Testen des Gesamtablaufs durch eine kleine Änderung an README.md

### ISSUE THREAD

**Issue by MicroEti** [netetireallyhuman/Html2Pdf#2]
Hallo,
ich würde gerne mal eine kompletten Gesamtablauf (Fork, Clone, Issue, Branch, Pullrequest) durchspielen und dafür eine kleine Änderung an README.md vornehmen.
Wäre das ok?
Gruß
MicroEti

**Comment by netetireallyhuman** [comment]
@MicroEti Das kommt mir auch gelegen, also leg los!👍
